#pragma once

enum keymap_keycodes {
    MACRO_COPY = QK_KB_4,
    MACRO_CUT,
    MACRO_DUPLICATE,
    MACRO_FOCUS_SPACE_LEFT,
    MACRO_FOCUS_SPACE_RIGHT,
    MACRO_FOCUS_TAB_LEFT,
    MACRO_FOCUS_TAB_RIGHT,
    MACRO_FOCUS_WINDOW_LEFT,
    MACRO_FOCUS_WINDOW_RIGHT,
    MACRO_GO_BACK,
    MACRO_GO_FORWARD,
    MACRO_PASTE,
    MACRO_REDO,
    MACRO_UNDO,
    ESC_TOGGLE_NAVIGATION_LAYER,
    DESKTOP_NAVIGATION,
    CUSTOM_DRAG_SCROLL,
    ZOOM_BUTTON_3,
    DPI_TOGGLE_SCROLL,
};
