#pragma once

#define RGB_MATRIX_DEFAULT_ON true

// Warm amber
#define RGB_MATRIX_DEFAULT_HUE 18
#define RGB_MATRIX_DEFAULT_SAT 240
#define RGB_MATRIX_DEFAULT_VAL 150

// Use solid color mode (mode 1 = RGB_MATRIX_SOLID_COLOR)
#define RGB_MATRIX_DEFAULT_MODE 1

#define USB_SUSPEND_WAKEUP_DELAY 200
#define USB_SUSPEND_WAKEUP_DELAY 200

#define WAIT_FOR_USB

