#pragma once

#define RGB_MATRIX_DEFAULT_ON true

// Warm amber
#define RGB_MATRIX_DEFAULT_HUE 18
#define RGB_MATRIX_DEFAULT_SAT 240
#define RGB_MATRIX_DEFAULT_VAL 150

// Use solid color mode (mode 1 = RGB_MATRIX_SOLID_COLOR)
#define RGB_MATRIX_DEFAULT_MODE 1

#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_WIDE
#define ENABLE_RGB_MATRIX_SOLID_REACTIVE_MULTIWIDE
#define ENABLE_RGB_MATRIX_MULTISPLASH
#define ENABLE_RGB_MATRIX_SOLID_MULTISPLASH

// USB connection stability fixes
#define WAIT_FOR_USB
#define USB_SUSPEND_WAKEUP_DELAY 500
#define USB_POLLING_INTERVAL_MS 10
#define USB_MAX_POWER_CONSUMPTION 100

